spring:
  application:
    name: api-gateway
  profiles:
    active: prod

  cloud:
    gateway:
      routes:
        - id: authentication-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<path>.*), /auth/$\{path}

        - id: farmrun-item-service
          uri: http://localhost:8082
          predicates:
            - Path=/farmrun/item/**
          filters:
            - AuthenticationFilter
            - RewritePath=/farmrun/item/(?<path>.*), /item/$\{path}