eureka:
  client:
    service-url:
      defaultZone : http://service-registry:8761/eureka/
services:
  authentication:
    url: http://authentication-service:8080

spring:
  cloud:
    gateway:
      routes:
        - id: authentication-service
          uri: http://authentication-service:8080
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<path>.*), /auth/$\{path}

        - id: farmrun-player-service
          uri: http://farmrun-player-service:8080
          predicates:
            - Path=/farmrun/player/**
          filters:
            - AuthenticationFilter
            - RewritePath=/farmrun/player/(?<path>.*), /player/$\{path}

        - id: farmrun-item-service
          uri: http://farmrun-item-service:8080
          predicates:
            - Path=/farmrun/item/**
          filters:
            - AuthenticationFilter
            - RewritePath=/farmrun/item/(?<path>.*), /item/$\{path}